### ISSUE TITLE
Voting doesn't work in mac

### ISSUE THREAD

**Issue by hagitgit** [yairchu/azlemi#1]
במק (כרום) ההצבעה לא עובדת
![screen shot 2015-01-20 at 1 45 21 pm](https://cloud.githubusercontent.com/assets/2655063/5816616/bd390bfe-a0aa-11e4-8aa1-d76b1fc38257.png)

**Comment by yairchu** [comment]
Thanks for the report - can you please also add the logs from the "View->Developer->Developer Tools->Console"?
These could be helpful for understanding what went wrong..

**Comment by hagitgit** [comment]
GET https://mysterious-thicket-1944.herokuapp.com/libs/json.js?v=20 404 (NOT FOUND)brython.js:7557 $download_modulebrython.js:7563 import_jsbrython.js:7679 import_from_stdlib_staticbrython.js:7755 $B.$importVM1045:14 (anonymous function)brython.js:4363 brython(index):56 onload
brython.js:7553 Error 404 means that Python module json was not found at url /libs/json.js
brython.js:7557 GET https://mysterious-thicket-1944.herokuapp.com/Lib/site-packages/json.py?v=21 404 (NOT FOUND)
brython.js:7553 Error 404 means that Python module json was not found at url /Lib/site-packages/json.py
brython.js:7557 GET https://mysterious-thicket-1944.herokuapp.com/Lib/site-packages/json/__init__.py?v=22 404 (NOT FOUND)
brython.js:7553 Error 404 means that Python module json was not found at url /Lib/site-packages/json/**init**.py
brython.js:7557 GET https://mysterious-thicket-1944.herokuapp.com/static/json.py?v=23 404 (NOT FOUND)
brython.js:7553 Error 404 means that Python module json was not found at url https://mysterious-thicket-1944.herokuapp.com/static/json.py
brython.js:7557 GET https://mysterious-thicket-1944.herokuapp.com/static/json/__init__.py?v=24 404 (NOT FOUND)
brython.js:7553 Error 404 means that Python module json was not found at url https://mysterious-thicket-1944.herokuapp.com/static/json/__init__.py
brython.js:7557 GET https://mysterious-thicket-1944.herokuapp.com/static//Lib/json.py?v=25 404 (NOT FOUND)
brython.js:7553 Error 404 means that Python module json was not found at url https://mysterious-thicket-1944.herokuapp.com/static//Lib/json.py
brython.js:7557 GET https://mysterious-thicket-1944.herokuapp.com/static//Lib/json/__init__.py?v=26 404 (NOT FOUND)
brython.js:7553 Error 404 means that Python module json was not found at url https://mysterious-thicket-1944.herokuapp.com/static//Lib/json/__init__.py
brython.js:7557 GET https://mysterious-thicket-1944.herokuapp.com/static//Lib/site-packages/json.py?v=27 404 (NOT FOUND)
brython.js:7553 Error 404 means that Python module json was not found at url https://mysterious-thicket-1944.herokuapp.com/static//Lib/site-packages/json.py
brython.js:7557 GET https://mysterious-thicket-1944.herokuapp.com/static//Lib/site-packages/json/__init__.py?v=28 404 (NOT FOUND)
brython.js:7553 Error 404 means that Python module json was not found at url https://mysterious-thicket-1944.herokuapp.com/static//Lib/site-packages/json/__init__.py
brython.js:5157 ImportError: cannot import json
Traceback (most recent call last):
  module **main** line 4
    import json
brython.js:4376 Uncaught Error: cannot import json

**Comment by yairchu** [comment]
Can you please try again now? thx!

**Comment by hagitgit** [comment]
it works now :)

**Comment by yairchu** [comment]
@hagits can you please check again on your system now?
I changed it to what is hopefully a proper solution for the problem following a comment from @PierreQuentel though need to check if it works (and on my envs it always worked..)
Cheers! Yair

**Comment by hagitgit** [comment]
It works :)
