### ISSUE TITLE
הצעות לתיקונים בעברית

### ISSUE THREAD

**Issue by hagitgit** [yairchu/azlemi#2]
1.
אתר זה מיועד לעזור לך לגלות איזו מפלגה מתאים לך להצביע. >>

אתר זה הוקם במטרה לעזור לך למצוא את המפלגה המייצגת יותר מכולן את עמדתך בנושאים פוליטיים, מדיניים, כלכליים וחברתיים.

2.
תענה על שאלות כדי לקבל תוצאות.. >>
ענו על שאלות כדי לצפות בתוצאות. ככל שתענו על מספר רב יותר של שאלות, תקבלו תוצאה מדוייקת יותר.

**Comment by yairchu** [comment]
שיניתי, תודה!
https://github.com/yairchu/vote_tool/commit/20a08d94963689778ab53a3c6c191bca0ad36358
