### ISSUE TITLE
שאלת מי יצר את open-vote

### ISSUE THREAD

**Issue by drorsnir** [yairchu/azlemi#3]
<div lang="he" dir="rtl">
[בעמוד "אתרים דומים"] ולא ראיתי מקום אחר לפנות אליך... לפי המידע של שם המתחם, מדובר בגיל זיידר (https://github.com/GilZ), שכנראה מעורב בפרויקטים של "הסדנא הפתוחה". נראה שגם open-vote הוא כלי פתוח -  ה-repo כאן: https://github.com/GilZ/open-vote.  
<br>
אם אתה צריך פרטי קשר נוספים, לפי linkedin הוא עובד ב-HP, כך שאני יכול לבקש מחברים ליצור קשר.
</div>

**Comment by yairchu** [comment]
תודה!
בקשר לפניות אליי, אפשר כאן, ואפשר גם בפייסבוק. ב״על האתר״ יש לינק לפייסבוק שלי

**Comment by drorsnir** [comment]
צודק, רק שאני נמנע מפייסבוק :-)

2015-02-03 2:48 GMT+02:00 Yair Chuchem notifications@github.com:
