### ISSUE TITLE
כפל מפלגות - "הרשימה המשותפת" ו"הרשימה הערבית"

### ISSUE THREAD

**Issue by drorsnir** [yairchu/azlemi#4]
<div lang="he" dir="rtl">
זו אותה מפלגה, לא? אבל שתיהן מופיעות בתוצאות שלי.
</div>

![duplicate](https://cloud.githubusercontent.com/assets/3416107/6012044/93549a14-ab4b-11e4-9866-bfd61e2fd0b7.png)

**Comment by yairchu** [comment]
זו לא אותה מפלגה.
״הרשימה הערבית״ היא רשימה חדשה ולא מוכרת בראשות טלב אלסאנה, שהיה ח״כ בכנסת ה 18 ולכן יש עליו (ולפיכך על הרשימה) מידע באזלמי.

המידע על הרשימות שמתמודדות מגיע מאתר ועדת הבחירות:
http://bechirot.gov.il/election/Candidates/Pages/default.aspx

לאחר שילוב המידע מועדת הבחירות הופתעתי גם אני לראות את הופעת המפלגה הזו עליה לא שמעתי.
אז כדי להפחית בלבול הוספתי כוכביות ליד שמה וגם ליד שמות המפלגות של כחלון וישי, עם דברי הסבר קצרים, וגם הוספתי לינקים למפלגות השונות. במקרה של ״הרשימה הערבית״, לא מצאתי לה אתר אינטרנט או אפילו איזכור בויקיפדיה (כן מופיעות בויקיפדיה המפלגות המרכיבות את הרשימה), אז הלינק מצביע לעמוד באתר ועדת הבחירות שבגללו בעצם הרשימה הזו מופיעה באזלמי..

**Comment by drorsnir** [comment]
מוזר... לפי אתר ועדת הבחירות:

"רשימת המועמדים הוגשה מטעם המפלגה הלאומית ערבית אל חיזב אלקאומי אלערבי
ומעטם _המפלגה הדמוקרטית הערבית_".

וויקיפדיה מוסיפה לגבי מד"ע:

> בשלהי כהונת הכנסת השמונה עשרה
> https://he.wikipedia.org/wiki/%D7%94%D7%9B%D7%A0%D7%A1%D7%AA_%D7%94%D7%A9%D7%9E%D7%95%D7%A0%D7%94_%D7%A2%D7%A9%D7%A8%D7%94
> ולקראת הבחירות לכנסת התשע עשרה
> https://he.wikipedia.org/wiki/%D7%94%D7%91%D7%97%D7%99%D7%A8%D7%95%D7%AA_%D7%9C%D7%9B%D7%A0%D7%A1%D7%AA_%D7%94%D7%AA%D7%A9%D7%A2_%D7%A2%D7%A9%D7%A8%D7%94
> פרש נציג המפלגה א-סאנע מן הסיעה המשותפת רע"מ-תע"ל
> https://he.wikipedia.org/wiki/%D7%A8%D7%A2%22%D7%9E-%D7%AA%D7%A2%22%D7%9C
> והקים את סיעת מד"ע מחדש, אולם בהמשך התרצה וחזר להתמודד לכנסת במסגרת המפלגה
> המאוחדת. ברשימה המשותפת של רע"ם-תע"ל-מד"ע בבחירות לכנסת התשע עשרה הוצב נציג
> מד"ע, א-סאנע, במקום החמישי. הרשימה קיבלה ארבעה מנדטים ולמד"ע לא נותר נציג
> בכנסת.

וחדשות 2 מוסיפים:

תוך כדי מסיבת העיתונאים התפרצו שני אנשים בצעקות, והפריעו מעט להרמוניה
שהתגבשה. אחד מהם טען שהוא נציג של המפלגה הערבית הדמוקרטית של ח"כ לשעבר טאלב
א-סאנע, וטען תוך כדי צעקות והתפרצות כי הרשימה הזו קברה את מפלגתו של א-סאנע.

שרפתי עכשיו כמעט שעה כדי לנסות להבין את זה, וזה עדיין לא ברור. כנראה שזו
מפלגה-שלא-בדיוק-קיימת-בפועל...

2015-02-03 2:45 GMT+02:00 Yair Chuchem notifications@github.com:

**Comment by drorsnir** [comment]
אה, אוקיי: http://www.nrg.co.il/online/1/ART2/672/983.html

**Comment by yairchu** [comment]
כן, זה מבלבל. עידכנתי את הלינק על המפלגה לקצרמר ויקיפדיה שזה עתה יצרתי בו קישרתי גם לכתבה שמצאת. תודה!
כמו כן אכתוב הסבר על איזה מפלגות מופיעות בו

**Comment by yairchu** [comment]
This just in:
טאלב א-סאנע פרש מהמירוץ
http://www.nrg.co.il/online/1/ART2/676/321.html
מה שמוציא אותו מהרשימה ועכשיו אין בה אנשים שיש עליהם מידע, ועל כן היא לא מדורגת יותר באתר
